export enum USER_AUTH_ACTIONS {
  CREATE_USER_LOAD =  'CREATE_USER_LOAD',
  CREATE_USER_SUCCESS =  'CREATE_USER_SUCCESS',
  CREATE_USER_FAIL =  'CREATE_USER_FAIL',

  GET_USER_LOAD =  'GET_USER_LOAD',
  GET_USER_SUCCESS =  'GET_USER_SUCCESS',
  GET_USER_FAIL =  'GET_USER_FAIL',
}
